example = 'Danil'
print (example [0])
print (example [-1])
print (example [2:5])
print (example [::-1])
print (example [1:5:2])
example = 'Топинамбур'
print (example [0])
print (example [-1])
print (example [5:10])
print (example [::-1])
print (example [1:10:2])